### ISSUE TITLE
Demo https://demo.leowgweb.com.br/grav/skeleton-klb4 does not work

### ISSUE THREAD

**Issue by awrog** [lauroguedes/grav-theme-klb4#4]
I'm very curiuos for this theme.
Unfortunately, the [demo-link](https://demo.leowgweb.com.br/grav/skeleton-klb4) does not work.

**Comment by diomed** [comment]
yes. demo is dead. 
can you maybe up it, @lauroguedes?

**Comment by lauroguedes** [comment]
Actually the demo is offline. Sorry, but I still work today.

**Comment by lauroguedes** [comment]
Link demo available - https://demo-grav-klb4-theme.herokuapp.com/

**Comment by awrog** [comment]
Nice and neat!
